[[IgnoredVulns]]
id = "CVE-2020-8203"
reason = "Package 'lodash.set@4.3.2' was fixed in another package (lodash), only version cannot be updated inside dependencies."

[[IgnoredVulns]]
id = "GHSA-3ppc-4f35-3m26"
reason = "Nested dependency minimatch attempt to override these versions would cause issue with build."

[[IgnoredVulns]]
id = "GHSA-93m4-6634-74q7"
reason = "Nested dependency vite attempt to override these versions would cause issue with build."

[[IgnoredVulns]]
id = "GHSA-g4jq-h2w9-997c"
reason = "Nested dependency vite attempt to override these versions would cause issue with build."

[[IgnoredVulns]]
id = "GHSA-jqfw-vq24-v9c3"
reason = "Nested dependency vite attempt to override these versions would cause issue with build."
